[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.0",
    "ipykernel>=7.2.0",
    "joblib>=1.5.0",
    "jupyter-collaboration==4.0.2",
    "jupyter-mcp-tools>=0.1.4",
    "jupyterlab==4.4.1",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "pycrdt>=0.12.50",
    "pydantic>=2.12.0",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.38.0",
]
